<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="tester-VirtualBox" name="zavrsni.Testovi.DodavanjeZgradeTest" tests="5" failures="0" timestamp="12 Jul 2019 10:33:59 GMT" time="19.845" errors="1">
  <testcase name="dodajZgradu" time="3.620" classname="zavrsni.Testovi.DodavanjeZgradeTest">
    <error type="java.lang.AssertionError" message="expected:&lt;Uspesno ste dodali zgradu!&gt; but was:&lt;&gt;">
      <![CDATA[java.lang.AssertionError: expected:<Uspesno ste dodali zgradu!> but was:<>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at org.testng.Assert.assertEquals(Assert.java:181)
	at zavrsni.Testovi.DodavanjeZgradeTest.dodajZgradu(DodavanjeZgradeTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- dodajZgradu -->
  <testcase name="daLiJeUTabeli" time="2.098" classname="zavrsni.Testovi.DodavanjeZgradeTest"/>
  <testcase name="dodajPrazno" time="0.954" classname="zavrsni.Testovi.DodavanjeZgradeTest"/>
  <testcase name="dodajIstuZgradu" time="12.047" classname="zavrsni.Testovi.DodavanjeZgradeTest"/>
  <testcase name="testReset" time="1.126" classname="zavrsni.Testovi.DodavanjeZgradeTest"/>
</testsuite> <!-- zavrsni.Testovi.DodavanjeZgradeTest -->
